default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: weather_map
  password: weather_map

development:
  <<: *default
  database: weather_map_development

test:
  <<: *default
  database: weather_map_test

production:
  <<: *default
  database: weather_map_production
